/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyResultsRouteImport } from './routes/weekly-results'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as LaneDataRouteImport } from './routes/lane-data'
import { Route as EliminationRouteImport } from './routes/elimination'
import { Route as BowlersRouteImport } from './routes/bowlers'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaderboardsIndexRouteImport } from './routes/leaderboards.index'
import { Route as SeasonsSeasonIdRouteImport } from './routes/seasons.$seasonId'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as LeaderboardsAdvancedRouteImport } from './routes/leaderboards.advanced'
import { Route as BowlersBowlerIdRouteImport } from './routes/bowlers.$bowlerId'
import { Route as AdminSeasonsRouteImport } from './routes/admin.seasons'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminPeopleRouteImport } from './routes/admin.people'
import { Route as AdminLiveScoringRouteImport } from './routes/admin.live-scoring'
import { Route as AdminBowlersRouteImport } from './routes/admin.bowlers'
import { Route as SeasonsSeasonIdIndexRouteImport } from './routes/seasons.$seasonId.index'
import { Route as AdminSeasonsIndexRouteImport } from './routes/admin.seasons.index'
import { Route as SeasonsSeasonIdStatisticsRouteImport } from './routes/seasons.$seasonId.statistics'
import { Route as SeasonsSeasonIdStandingsRouteImport } from './routes/seasons.$seasonId.standings'
import { Route as SeasonsSeasonIdScheduleRouteImport } from './routes/seasons.$seasonId.schedule'
import { Route as SeasonsSeasonIdResultsRouteImport } from './routes/seasons.$seasonId.results'
import { Route as BowlersSubSubstituteIdRouteImport } from './routes/bowlers.sub.$substituteId'
import { Route as AdminSeasonsSeasonIdRouteImport } from './routes/admin.seasons.$seasonId'
import { Route as SeasonsSeasonIdBowlersParticipantRefRouteImport } from './routes/seasons.$seasonId.bowlers.$participantRef'

const WeeklyResultsRoute = WeeklyResultsRouteImport.update({
  id: '/weekly-results',
  path: '/weekly-results',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const LaneDataRoute = LaneDataRouteImport.update({
  id: '/lane-data',
  path: '/lane-data',
  getParentRoute: () => rootRouteImport,
} as any)
const EliminationRoute = EliminationRouteImport.update({
  id: '/elimination',
  path: '/elimination',
  getParentRoute: () => rootRouteImport,
} as any)
const BowlersRoute = BowlersRouteImport.update({
  id: '/bowlers',
  path: '/bowlers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsIndexRoute = LeaderboardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeaderboardsRoute,
} as any)
const SeasonsSeasonIdRoute = SeasonsSeasonIdRouteImport.update({
  id: '/$seasonId',
  path: '/$seasonId',
  getParentRoute: () => SeasonsRoute,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsAdvancedRoute = LeaderboardsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => LeaderboardsRoute,
} as any)
const BowlersBowlerIdRoute = BowlersBowlerIdRouteImport.update({
  id: '/$bowlerId',
  path: '/$bowlerId',
  getParentRoute: () => BowlersRoute,
} as any)
const AdminSeasonsRoute = AdminSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveScoringRoute = AdminLiveScoringRouteImport.update({
  id: '/live-scoring',
  path: '/live-scoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBowlersRoute = AdminBowlersRouteImport.update({
  id: '/bowlers',
  path: '/bowlers',
  getParentRoute: () => AdminRoute,
} as any)
const SeasonsSeasonIdIndexRoute = SeasonsSeasonIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeasonsSeasonIdRoute,
} as any)
const AdminSeasonsIndexRoute = AdminSeasonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSeasonsRoute,
} as any)
const SeasonsSeasonIdStatisticsRoute =
  SeasonsSeasonIdStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => SeasonsSeasonIdRoute,
  } as any)
const SeasonsSeasonIdStandingsRoute =
  SeasonsSeasonIdStandingsRouteImport.update({
    id: '/standings',
    path: '/standings',
    getParentRoute: () => SeasonsSeasonIdRoute,
  } as any)
const SeasonsSeasonIdScheduleRoute = SeasonsSeasonIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => SeasonsSeasonIdRoute,
} as any)
const SeasonsSeasonIdResultsRoute = SeasonsSeasonIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SeasonsSeasonIdRoute,
} as any)
const BowlersSubSubstituteIdRoute = BowlersSubSubstituteIdRouteImport.update({
  id: '/sub/$substituteId',
  path: '/sub/$substituteId',
  getParentRoute: () => BowlersRoute,
} as any)
const AdminSeasonsSeasonIdRoute = AdminSeasonsSeasonIdRouteImport.update({
  id: '/$seasonId',
  path: '/$seasonId',
  getParentRoute: () => AdminSeasonsRoute,
} as any)
const SeasonsSeasonIdBowlersParticipantRefRoute =
  SeasonsSeasonIdBowlersParticipantRefRouteImport.update({
    id: '/bowlers/$participantRef',
    path: '/bowlers/$participantRef',
    getParentRoute: () => SeasonsSeasonIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/bowlers': typeof BowlersRouteWithChildren
  '/elimination': typeof EliminationRoute
  '/lane-data': typeof LaneDataRoute
  '/leaderboards': typeof LeaderboardsRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/seasons': typeof SeasonsRouteWithChildren
  '/standings': typeof StandingsRoute
  '/statistics': typeof StatisticsRoute
  '/weekly-results': typeof WeeklyResultsRoute
  '/admin/bowlers': typeof AdminBowlersRoute
  '/admin/live-scoring': typeof AdminLiveScoringRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/seasons': typeof AdminSeasonsRouteWithChildren
  '/bowlers/$bowlerId': typeof BowlersBowlerIdRoute
  '/leaderboards/advanced': typeof LeaderboardsAdvancedRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/seasons/$seasonId': typeof SeasonsSeasonIdRouteWithChildren
  '/leaderboards/': typeof LeaderboardsIndexRoute
  '/admin/seasons/$seasonId': typeof AdminSeasonsSeasonIdRoute
  '/bowlers/sub/$substituteId': typeof BowlersSubSubstituteIdRoute
  '/seasons/$seasonId/results': typeof SeasonsSeasonIdResultsRoute
  '/seasons/$seasonId/schedule': typeof SeasonsSeasonIdScheduleRoute
  '/seasons/$seasonId/standings': typeof SeasonsSeasonIdStandingsRoute
  '/seasons/$seasonId/statistics': typeof SeasonsSeasonIdStatisticsRoute
  '/admin/seasons/': typeof AdminSeasonsIndexRoute
  '/seasons/$seasonId/': typeof SeasonsSeasonIdIndexRoute
  '/seasons/$seasonId/bowlers/$participantRef': typeof SeasonsSeasonIdBowlersParticipantRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/bowlers': typeof BowlersRouteWithChildren
  '/elimination': typeof EliminationRoute
  '/lane-data': typeof LaneDataRoute
  '/schedule': typeof ScheduleRoute
  '/seasons': typeof SeasonsRouteWithChildren
  '/standings': typeof StandingsRoute
  '/statistics': typeof StatisticsRoute
  '/weekly-results': typeof WeeklyResultsRoute
  '/admin/bowlers': typeof AdminBowlersRoute
  '/admin/live-scoring': typeof AdminLiveScoringRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/bowlers/$bowlerId': typeof BowlersBowlerIdRoute
  '/leaderboards/advanced': typeof LeaderboardsAdvancedRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/leaderboards': typeof LeaderboardsIndexRoute
  '/admin/seasons/$seasonId': typeof AdminSeasonsSeasonIdRoute
  '/bowlers/sub/$substituteId': typeof BowlersSubSubstituteIdRoute
  '/seasons/$seasonId/results': typeof SeasonsSeasonIdResultsRoute
  '/seasons/$seasonId/schedule': typeof SeasonsSeasonIdScheduleRoute
  '/seasons/$seasonId/standings': typeof SeasonsSeasonIdStandingsRoute
  '/seasons/$seasonId/statistics': typeof SeasonsSeasonIdStatisticsRoute
  '/admin/seasons': typeof AdminSeasonsIndexRoute
  '/seasons/$seasonId': typeof SeasonsSeasonIdIndexRoute
  '/seasons/$seasonId/bowlers/$participantRef': typeof SeasonsSeasonIdBowlersParticipantRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/bowlers': typeof BowlersRouteWithChildren
  '/elimination': typeof EliminationRoute
  '/lane-data': typeof LaneDataRoute
  '/leaderboards': typeof LeaderboardsRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/seasons': typeof SeasonsRouteWithChildren
  '/standings': typeof StandingsRoute
  '/statistics': typeof StatisticsRoute
  '/weekly-results': typeof WeeklyResultsRoute
  '/admin/bowlers': typeof AdminBowlersRoute
  '/admin/live-scoring': typeof AdminLiveScoringRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/seasons': typeof AdminSeasonsRouteWithChildren
  '/bowlers/$bowlerId': typeof BowlersBowlerIdRoute
  '/leaderboards/advanced': typeof LeaderboardsAdvancedRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/seasons/$seasonId': typeof SeasonsSeasonIdRouteWithChildren
  '/leaderboards/': typeof LeaderboardsIndexRoute
  '/admin/seasons/$seasonId': typeof AdminSeasonsSeasonIdRoute
  '/bowlers/sub/$substituteId': typeof BowlersSubSubstituteIdRoute
  '/seasons/$seasonId/results': typeof SeasonsSeasonIdResultsRoute
  '/seasons/$seasonId/schedule': typeof SeasonsSeasonIdScheduleRoute
  '/seasons/$seasonId/standings': typeof SeasonsSeasonIdStandingsRoute
  '/seasons/$seasonId/statistics': typeof SeasonsSeasonIdStatisticsRoute
  '/admin/seasons/': typeof AdminSeasonsIndexRoute
  '/seasons/$seasonId/': typeof SeasonsSeasonIdIndexRoute
  '/seasons/$seasonId/bowlers/$participantRef': typeof SeasonsSeasonIdBowlersParticipantRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/bowlers'
    | '/elimination'
    | '/lane-data'
    | '/leaderboards'
    | '/schedule'
    | '/seasons'
    | '/standings'
    | '/statistics'
    | '/weekly-results'
    | '/admin/bowlers'
    | '/admin/live-scoring'
    | '/admin/people'
    | '/admin/results'
    | '/admin/schedule'
    | '/admin/seasons'
    | '/bowlers/$bowlerId'
    | '/leaderboards/advanced'
    | '/people/$personId'
    | '/seasons/$seasonId'
    | '/leaderboards/'
    | '/admin/seasons/$seasonId'
    | '/bowlers/sub/$substituteId'
    | '/seasons/$seasonId/results'
    | '/seasons/$seasonId/schedule'
    | '/seasons/$seasonId/standings'
    | '/seasons/$seasonId/statistics'
    | '/admin/seasons/'
    | '/seasons/$seasonId/'
    | '/seasons/$seasonId/bowlers/$participantRef'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/bowlers'
    | '/elimination'
    | '/lane-data'
    | '/schedule'
    | '/seasons'
    | '/standings'
    | '/statistics'
    | '/weekly-results'
    | '/admin/bowlers'
    | '/admin/live-scoring'
    | '/admin/people'
    | '/admin/results'
    | '/admin/schedule'
    | '/bowlers/$bowlerId'
    | '/leaderboards/advanced'
    | '/people/$personId'
    | '/leaderboards'
    | '/admin/seasons/$seasonId'
    | '/bowlers/sub/$substituteId'
    | '/seasons/$seasonId/results'
    | '/seasons/$seasonId/schedule'
    | '/seasons/$seasonId/standings'
    | '/seasons/$seasonId/statistics'
    | '/admin/seasons'
    | '/seasons/$seasonId'
    | '/seasons/$seasonId/bowlers/$participantRef'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/bowlers'
    | '/elimination'
    | '/lane-data'
    | '/leaderboards'
    | '/schedule'
    | '/seasons'
    | '/standings'
    | '/statistics'
    | '/weekly-results'
    | '/admin/bowlers'
    | '/admin/live-scoring'
    | '/admin/people'
    | '/admin/results'
    | '/admin/schedule'
    | '/admin/seasons'
    | '/bowlers/$bowlerId'
    | '/leaderboards/advanced'
    | '/people/$personId'
    | '/seasons/$seasonId'
    | '/leaderboards/'
    | '/admin/seasons/$seasonId'
    | '/bowlers/sub/$substituteId'
    | '/seasons/$seasonId/results'
    | '/seasons/$seasonId/schedule'
    | '/seasons/$seasonId/standings'
    | '/seasons/$seasonId/statistics'
    | '/admin/seasons/'
    | '/seasons/$seasonId/'
    | '/seasons/$seasonId/bowlers/$participantRef'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BowlersRoute: typeof BowlersRouteWithChildren
  EliminationRoute: typeof EliminationRoute
  LaneDataRoute: typeof LaneDataRoute
  LeaderboardsRoute: typeof LeaderboardsRouteWithChildren
  ScheduleRoute: typeof ScheduleRoute
  SeasonsRoute: typeof SeasonsRouteWithChildren
  StandingsRoute: typeof StandingsRoute
  StatisticsRoute: typeof StatisticsRoute
  WeeklyResultsRoute: typeof WeeklyResultsRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-results': {
      id: '/weekly-results'
      path: '/weekly-results'
      fullPath: '/weekly-results'
      preLoaderRoute: typeof WeeklyResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lane-data': {
      id: '/lane-data'
      path: '/lane-data'
      fullPath: '/lane-data'
      preLoaderRoute: typeof LaneDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elimination': {
      id: '/elimination'
      path: '/elimination'
      fullPath: '/elimination'
      preLoaderRoute: typeof EliminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bowlers': {
      id: '/bowlers'
      path: '/bowlers'
      fullPath: '/bowlers'
      preLoaderRoute: typeof BowlersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards/': {
      id: '/leaderboards/'
      path: '/'
      fullPath: '/leaderboards/'
      preLoaderRoute: typeof LeaderboardsIndexRouteImport
      parentRoute: typeof LeaderboardsRoute
    }
    '/seasons/$seasonId': {
      id: '/seasons/$seasonId'
      path: '/$seasonId'
      fullPath: '/seasons/$seasonId'
      preLoaderRoute: typeof SeasonsSeasonIdRouteImport
      parentRoute: typeof SeasonsRoute
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards/advanced': {
      id: '/leaderboards/advanced'
      path: '/advanced'
      fullPath: '/leaderboards/advanced'
      preLoaderRoute: typeof LeaderboardsAdvancedRouteImport
      parentRoute: typeof LeaderboardsRoute
    }
    '/bowlers/$bowlerId': {
      id: '/bowlers/$bowlerId'
      path: '/$bowlerId'
      fullPath: '/bowlers/$bowlerId'
      preLoaderRoute: typeof BowlersBowlerIdRouteImport
      parentRoute: typeof BowlersRoute
    }
    '/admin/seasons': {
      id: '/admin/seasons'
      path: '/seasons'
      fullPath: '/admin/seasons'
      preLoaderRoute: typeof AdminSeasonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-scoring': {
      id: '/admin/live-scoring'
      path: '/live-scoring'
      fullPath: '/admin/live-scoring'
      preLoaderRoute: typeof AdminLiveScoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bowlers': {
      id: '/admin/bowlers'
      path: '/bowlers'
      fullPath: '/admin/bowlers'
      preLoaderRoute: typeof AdminBowlersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seasons/$seasonId/': {
      id: '/seasons/$seasonId/'
      path: '/'
      fullPath: '/seasons/$seasonId/'
      preLoaderRoute: typeof SeasonsSeasonIdIndexRouteImport
      parentRoute: typeof SeasonsSeasonIdRoute
    }
    '/admin/seasons/': {
      id: '/admin/seasons/'
      path: '/'
      fullPath: '/admin/seasons/'
      preLoaderRoute: typeof AdminSeasonsIndexRouteImport
      parentRoute: typeof AdminSeasonsRoute
    }
    '/seasons/$seasonId/statistics': {
      id: '/seasons/$seasonId/statistics'
      path: '/statistics'
      fullPath: '/seasons/$seasonId/statistics'
      preLoaderRoute: typeof SeasonsSeasonIdStatisticsRouteImport
      parentRoute: typeof SeasonsSeasonIdRoute
    }
    '/seasons/$seasonId/standings': {
      id: '/seasons/$seasonId/standings'
      path: '/standings'
      fullPath: '/seasons/$seasonId/standings'
      preLoaderRoute: typeof SeasonsSeasonIdStandingsRouteImport
      parentRoute: typeof SeasonsSeasonIdRoute
    }
    '/seasons/$seasonId/schedule': {
      id: '/seasons/$seasonId/schedule'
      path: '/schedule'
      fullPath: '/seasons/$seasonId/schedule'
      preLoaderRoute: typeof SeasonsSeasonIdScheduleRouteImport
      parentRoute: typeof SeasonsSeasonIdRoute
    }
    '/seasons/$seasonId/results': {
      id: '/seasons/$seasonId/results'
      path: '/results'
      fullPath: '/seasons/$seasonId/results'
      preLoaderRoute: typeof SeasonsSeasonIdResultsRouteImport
      parentRoute: typeof SeasonsSeasonIdRoute
    }
    '/bowlers/sub/$substituteId': {
      id: '/bowlers/sub/$substituteId'
      path: '/sub/$substituteId'
      fullPath: '/bowlers/sub/$substituteId'
      preLoaderRoute: typeof BowlersSubSubstituteIdRouteImport
      parentRoute: typeof BowlersRoute
    }
    '/admin/seasons/$seasonId': {
      id: '/admin/seasons/$seasonId'
      path: '/$seasonId'
      fullPath: '/admin/seasons/$seasonId'
      preLoaderRoute: typeof AdminSeasonsSeasonIdRouteImport
      parentRoute: typeof AdminSeasonsRoute
    }
    '/seasons/$seasonId/bowlers/$participantRef': {
      id: '/seasons/$seasonId/bowlers/$participantRef'
      path: '/bowlers/$participantRef'
      fullPath: '/seasons/$seasonId/bowlers/$participantRef'
      preLoaderRoute: typeof SeasonsSeasonIdBowlersParticipantRefRouteImport
      parentRoute: typeof SeasonsSeasonIdRoute
    }
  }
}

interface AdminSeasonsRouteChildren {
  AdminSeasonsSeasonIdRoute: typeof AdminSeasonsSeasonIdRoute
  AdminSeasonsIndexRoute: typeof AdminSeasonsIndexRoute
}

const AdminSeasonsRouteChildren: AdminSeasonsRouteChildren = {
  AdminSeasonsSeasonIdRoute: AdminSeasonsSeasonIdRoute,
  AdminSeasonsIndexRoute: AdminSeasonsIndexRoute,
}

const AdminSeasonsRouteWithChildren = AdminSeasonsRoute._addFileChildren(
  AdminSeasonsRouteChildren,
)

interface AdminRouteChildren {
  AdminBowlersRoute: typeof AdminBowlersRoute
  AdminLiveScoringRoute: typeof AdminLiveScoringRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSeasonsRoute: typeof AdminSeasonsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBowlersRoute: AdminBowlersRoute,
  AdminLiveScoringRoute: AdminLiveScoringRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSeasonsRoute: AdminSeasonsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BowlersRouteChildren {
  BowlersBowlerIdRoute: typeof BowlersBowlerIdRoute
  BowlersSubSubstituteIdRoute: typeof BowlersSubSubstituteIdRoute
}

const BowlersRouteChildren: BowlersRouteChildren = {
  BowlersBowlerIdRoute: BowlersBowlerIdRoute,
  BowlersSubSubstituteIdRoute: BowlersSubSubstituteIdRoute,
}

const BowlersRouteWithChildren =
  BowlersRoute._addFileChildren(BowlersRouteChildren)

interface LeaderboardsRouteChildren {
  LeaderboardsAdvancedRoute: typeof LeaderboardsAdvancedRoute
  LeaderboardsIndexRoute: typeof LeaderboardsIndexRoute
}

const LeaderboardsRouteChildren: LeaderboardsRouteChildren = {
  LeaderboardsAdvancedRoute: LeaderboardsAdvancedRoute,
  LeaderboardsIndexRoute: LeaderboardsIndexRoute,
}

const LeaderboardsRouteWithChildren = LeaderboardsRoute._addFileChildren(
  LeaderboardsRouteChildren,
)

interface SeasonsSeasonIdRouteChildren {
  SeasonsSeasonIdResultsRoute: typeof SeasonsSeasonIdResultsRoute
  SeasonsSeasonIdScheduleRoute: typeof SeasonsSeasonIdScheduleRoute
  SeasonsSeasonIdStandingsRoute: typeof SeasonsSeasonIdStandingsRoute
  SeasonsSeasonIdStatisticsRoute: typeof SeasonsSeasonIdStatisticsRoute
  SeasonsSeasonIdIndexRoute: typeof SeasonsSeasonIdIndexRoute
  SeasonsSeasonIdBowlersParticipantRefRoute: typeof SeasonsSeasonIdBowlersParticipantRefRoute
}

const SeasonsSeasonIdRouteChildren: SeasonsSeasonIdRouteChildren = {
  SeasonsSeasonIdResultsRoute: SeasonsSeasonIdResultsRoute,
  SeasonsSeasonIdScheduleRoute: SeasonsSeasonIdScheduleRoute,
  SeasonsSeasonIdStandingsRoute: SeasonsSeasonIdStandingsRoute,
  SeasonsSeasonIdStatisticsRoute: SeasonsSeasonIdStatisticsRoute,
  SeasonsSeasonIdIndexRoute: SeasonsSeasonIdIndexRoute,
  SeasonsSeasonIdBowlersParticipantRefRoute:
    SeasonsSeasonIdBowlersParticipantRefRoute,
}

const SeasonsSeasonIdRouteWithChildren = SeasonsSeasonIdRoute._addFileChildren(
  SeasonsSeasonIdRouteChildren,
)

interface SeasonsRouteChildren {
  SeasonsSeasonIdRoute: typeof SeasonsSeasonIdRouteWithChildren
}

const SeasonsRouteChildren: SeasonsRouteChildren = {
  SeasonsSeasonIdRoute: SeasonsSeasonIdRouteWithChildren,
}

const SeasonsRouteWithChildren =
  SeasonsRoute._addFileChildren(SeasonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BowlersRoute: BowlersRouteWithChildren,
  EliminationRoute: EliminationRoute,
  LaneDataRoute: LaneDataRoute,
  LeaderboardsRoute: LeaderboardsRouteWithChildren,
  ScheduleRoute: ScheduleRoute,
  SeasonsRoute: SeasonsRouteWithChildren,
  StandingsRoute: StandingsRoute,
  StatisticsRoute: StatisticsRoute,
  WeeklyResultsRoute: WeeklyResultsRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
