/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyResultsRouteImport } from './routes/weekly-results'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as LaneDataRouteImport } from './routes/lane-data'
import { Route as EliminationRouteImport } from './routes/elimination'
import { Route as BowlersRouteImport } from './routes/bowlers'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaderboardsIndexRouteImport } from './routes/leaderboards.index'
import { Route as LeaderboardsAdvancedRouteImport } from './routes/leaderboards.advanced'
import { Route as BowlersBowlerIdRouteImport } from './routes/bowlers.$bowlerId'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminBowlersRouteImport } from './routes/admin.bowlers'

const WeeklyResultsRoute = WeeklyResultsRouteImport.update({
  id: '/weekly-results',
  path: '/weekly-results',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const LaneDataRoute = LaneDataRouteImport.update({
  id: '/lane-data',
  path: '/lane-data',
  getParentRoute: () => rootRouteImport,
} as any)
const EliminationRoute = EliminationRouteImport.update({
  id: '/elimination',
  path: '/elimination',
  getParentRoute: () => rootRouteImport,
} as any)
const BowlersRoute = BowlersRouteImport.update({
  id: '/bowlers',
  path: '/bowlers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsIndexRoute = LeaderboardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeaderboardsRoute,
} as any)
const LeaderboardsAdvancedRoute = LeaderboardsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => LeaderboardsRoute,
} as any)
const BowlersBowlerIdRoute = BowlersBowlerIdRouteImport.update({
  id: '/$bowlerId',
  path: '/$bowlerId',
  getParentRoute: () => BowlersRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/admin/schedule',
  path: '/admin/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/admin/results',
  path: '/admin/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBowlersRoute = AdminBowlersRouteImport.update({
  id: '/admin/bowlers',
  path: '/admin/bowlers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/bowlers': typeof BowlersRouteWithChildren
  '/elimination': typeof EliminationRoute
  '/lane-data': typeof LaneDataRoute
  '/leaderboards': typeof LeaderboardsRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/standings': typeof StandingsRoute
  '/statistics': typeof StatisticsRoute
  '/weekly-results': typeof WeeklyResultsRoute
  '/admin/bowlers': typeof AdminBowlersRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/bowlers/$bowlerId': typeof BowlersBowlerIdRoute
  '/leaderboards/advanced': typeof LeaderboardsAdvancedRoute
  '/leaderboards/': typeof LeaderboardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/bowlers': typeof BowlersRouteWithChildren
  '/elimination': typeof EliminationRoute
  '/lane-data': typeof LaneDataRoute
  '/schedule': typeof ScheduleRoute
  '/standings': typeof StandingsRoute
  '/statistics': typeof StatisticsRoute
  '/weekly-results': typeof WeeklyResultsRoute
  '/admin/bowlers': typeof AdminBowlersRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/bowlers/$bowlerId': typeof BowlersBowlerIdRoute
  '/leaderboards/advanced': typeof LeaderboardsAdvancedRoute
  '/leaderboards': typeof LeaderboardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/bowlers': typeof BowlersRouteWithChildren
  '/elimination': typeof EliminationRoute
  '/lane-data': typeof LaneDataRoute
  '/leaderboards': typeof LeaderboardsRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/standings': typeof StandingsRoute
  '/statistics': typeof StatisticsRoute
  '/weekly-results': typeof WeeklyResultsRoute
  '/admin/bowlers': typeof AdminBowlersRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/bowlers/$bowlerId': typeof BowlersBowlerIdRoute
  '/leaderboards/advanced': typeof LeaderboardsAdvancedRoute
  '/leaderboards/': typeof LeaderboardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/bowlers'
    | '/elimination'
    | '/lane-data'
    | '/leaderboards'
    | '/schedule'
    | '/standings'
    | '/statistics'
    | '/weekly-results'
    | '/admin/bowlers'
    | '/admin/results'
    | '/admin/schedule'
    | '/bowlers/$bowlerId'
    | '/leaderboards/advanced'
    | '/leaderboards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/bowlers'
    | '/elimination'
    | '/lane-data'
    | '/schedule'
    | '/standings'
    | '/statistics'
    | '/weekly-results'
    | '/admin/bowlers'
    | '/admin/results'
    | '/admin/schedule'
    | '/bowlers/$bowlerId'
    | '/leaderboards/advanced'
    | '/leaderboards'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/bowlers'
    | '/elimination'
    | '/lane-data'
    | '/leaderboards'
    | '/schedule'
    | '/standings'
    | '/statistics'
    | '/weekly-results'
    | '/admin/bowlers'
    | '/admin/results'
    | '/admin/schedule'
    | '/bowlers/$bowlerId'
    | '/leaderboards/advanced'
    | '/leaderboards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BowlersRoute: typeof BowlersRouteWithChildren
  EliminationRoute: typeof EliminationRoute
  LaneDataRoute: typeof LaneDataRoute
  LeaderboardsRoute: typeof LeaderboardsRouteWithChildren
  ScheduleRoute: typeof ScheduleRoute
  StandingsRoute: typeof StandingsRoute
  StatisticsRoute: typeof StatisticsRoute
  WeeklyResultsRoute: typeof WeeklyResultsRoute
  AdminBowlersRoute: typeof AdminBowlersRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-results': {
      id: '/weekly-results'
      path: '/weekly-results'
      fullPath: '/weekly-results'
      preLoaderRoute: typeof WeeklyResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lane-data': {
      id: '/lane-data'
      path: '/lane-data'
      fullPath: '/lane-data'
      preLoaderRoute: typeof LaneDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elimination': {
      id: '/elimination'
      path: '/elimination'
      fullPath: '/elimination'
      preLoaderRoute: typeof EliminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bowlers': {
      id: '/bowlers'
      path: '/bowlers'
      fullPath: '/bowlers'
      preLoaderRoute: typeof BowlersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards/': {
      id: '/leaderboards/'
      path: '/'
      fullPath: '/leaderboards/'
      preLoaderRoute: typeof LeaderboardsIndexRouteImport
      parentRoute: typeof LeaderboardsRoute
    }
    '/leaderboards/advanced': {
      id: '/leaderboards/advanced'
      path: '/advanced'
      fullPath: '/leaderboards/advanced'
      preLoaderRoute: typeof LeaderboardsAdvancedRouteImport
      parentRoute: typeof LeaderboardsRoute
    }
    '/bowlers/$bowlerId': {
      id: '/bowlers/$bowlerId'
      path: '/$bowlerId'
      fullPath: '/bowlers/$bowlerId'
      preLoaderRoute: typeof BowlersBowlerIdRouteImport
      parentRoute: typeof BowlersRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/admin/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bowlers': {
      id: '/admin/bowlers'
      path: '/admin/bowlers'
      fullPath: '/admin/bowlers'
      preLoaderRoute: typeof AdminBowlersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BowlersRouteChildren {
  BowlersBowlerIdRoute: typeof BowlersBowlerIdRoute
}

const BowlersRouteChildren: BowlersRouteChildren = {
  BowlersBowlerIdRoute: BowlersBowlerIdRoute,
}

const BowlersRouteWithChildren =
  BowlersRoute._addFileChildren(BowlersRouteChildren)

interface LeaderboardsRouteChildren {
  LeaderboardsAdvancedRoute: typeof LeaderboardsAdvancedRoute
  LeaderboardsIndexRoute: typeof LeaderboardsIndexRoute
}

const LeaderboardsRouteChildren: LeaderboardsRouteChildren = {
  LeaderboardsAdvancedRoute: LeaderboardsAdvancedRoute,
  LeaderboardsIndexRoute: LeaderboardsIndexRoute,
}

const LeaderboardsRouteWithChildren = LeaderboardsRoute._addFileChildren(
  LeaderboardsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  BowlersRoute: BowlersRouteWithChildren,
  EliminationRoute: EliminationRoute,
  LaneDataRoute: LaneDataRoute,
  LeaderboardsRoute: LeaderboardsRouteWithChildren,
  ScheduleRoute: ScheduleRoute,
  StandingsRoute: StandingsRoute,
  StatisticsRoute: StatisticsRoute,
  WeeklyResultsRoute: WeeklyResultsRoute,
  AdminBowlersRoute: AdminBowlersRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminScheduleRoute: AdminScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
