// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsdsvboenycuqeihaqjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzZHN2Ym9lbnljdXFlaWhhcWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQwMzk1ODUsImV4cCI6MjA5OTYxNTU4NX0.6atEjAr368HMgpyWREFzqNtLptsuCQW7lVmRBQaPLo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});